Feature/build
altendky/ccstudio-dss pull request #1
Opened 2018-09-21 13:59 UTC by toddsnider-epc

Move build functionality from grid-tied.

2018-09-21 14:14 UTC, altendky approved these changes

2018-09-21 14:14 UTC, altendky commented on .project
> +</projectDescription>
I'll let adding these slide.  :]

2018-09-22 00:14 UTC, altendky requested changes
`build_type_choices` probably belongs in `api` and should become an enumeration now that it can be selected by something other than CLI text.

2018-09-25 21:58 UTC, toddsnider-epc commented
https://github.com/pallets/click/issues/605

2018-09-25 22:17 UTC, toddsnider-epc commented
epcpower/ccstudiodss/commit/0641a7d5924b5ba1686f6b7f70ec881b1b6e998d

2018-09-25 23:54 UTC, altendky commented
Sorry, see the click link now.  Hers the basic conversion but I'll gander through the link for something niftier. Maybe an actual click type.

```python3
build_type_strings = [build_type.name for build_type in Build types]

build_type = BuildTypes[chosen_string]
```

2018-09-26 00:30 UTC, altendky commented
Yeah, no named tuple.  Stdlib Enum or enum34 from PyPI.  Either PR for Click similar to the last suggestion in the ticket or something like I have above.  I haven't contributed to click so I don't know how the process goes with them.

2018-09-26 18:41 UTC, altendky approved these changes

2018-09-26 18:41 UTC, altendky commented
Note that GitHub inserts the commits into the history here so no need to link them.

2018-09-26 18:41 UTC, merged